### ISSUE TITLE
Issue with fish shell

### ISSUE THREAD

**Issue by andersennl** [gbaptista/sublime-3-shell-exec#3]
Just wanted to let you know, when using fish shell [fishshell.com](http://fishshell.com), I get this error when using your package:

``` bash
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
```

**Comment by andersennl** [comment]
I'd like to create a pull request to integrate fish-shell support. Would that be ok?

**Comment by alagiboy** [comment]
@andersennl  I am having the same issue as-well, please share if you've found a solution for this.

**Comment by gbaptista** [comment]
@andersennl Absolutely! =)

**Comment by andersennl** [comment]
@alagiboy I haven't directly found a solution which will immediately work for us but I'll hurry creating a branch which checks for fish and then uses a different initialize command.

**Comment by alessandro-fazzi** [comment]
Same problem here
